[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
judgechain = "9vBoPV2ZzcbVPWGzJhA31SDYRZ3efwLZ2HH6BfBLvnm2"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -r ts-node/register tests/**/*.ts"

[hooks]
