"""initial_schema

Revision ID: 90d6ccd1005d
Revises: 
Create Date: 2026-04-18 21:41:47.122199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d6ccd1005d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackathons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organizer_wallet', sa.String(), nullable=False),
    sa.Column('problems', sa.JSON(), nullable=True),
    sa.Column('scoring_weights', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('finalized_at', sa.Integer(), nullable=True),
    sa.Column('on_chain_tx', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('wallet', sa.String(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('injection_attempts', sa.JSON(), nullable=True),
    sa.Column('injection_threat_level', sa.String(), nullable=False),
    sa.Column('content_hash_pre_sanitize', sa.String(), nullable=False),
    sa.Column('content_hash_post_sanitize', sa.String(), nullable=False),
    sa.Column('gaming_flags', sa.JSON(), nullable=True),
    sa.Column('score_penalties_applied', sa.Integer(), nullable=True),
    sa.Column('raw_system_score', sa.Integer(), nullable=False),
    sa.Column('final_system_score', sa.Integer(), nullable=False),
    sa.Column('was_penalized', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_audit_id'), 'security_audit', ['id'], unique=False)
    op.create_index(op.f('ix_security_audit_submission_id'), 'security_audit', ['submission_id'], unique=False)
    op.create_index(op.f('ix_security_audit_timestamp'), 'security_audit', ['timestamp'], unique=False)
    op.create_index(op.f('ix_security_audit_wallet'), 'security_audit', ['wallet'], unique=False)
    op.create_table('submissions',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('problem_id', sa.String(), nullable=False),
    sa.Column('wallet', sa.String(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('deployment_url', sa.String(), nullable=False),
    sa.Column('score_code_quality', sa.Integer(), nullable=False),
    sa.Column('score_test_coverage', sa.Integer(), nullable=False),
    sa.Column('score_deployment_health', sa.Integer(), nullable=False),
    sa.Column('score_documentation', sa.Integer(), nullable=False),
    sa.Column('score_custom_criteria', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('judge_score', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('judge_submitted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_index(op.f('ix_submissions_problem_id'), 'submissions', ['problem_id'], unique=False)
    op.create_index(op.f('ix_submissions_wallet'), 'submissions', ['wallet'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_wallet'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_problem_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_security_audit_wallet'), table_name='security_audit')
    op.drop_index(op.f('ix_security_audit_timestamp'), table_name='security_audit')
    op.drop_index(op.f('ix_security_audit_submission_id'), table_name='security_audit')
    op.drop_index(op.f('ix_security_audit_id'), table_name='security_audit')
    op.drop_table('security_audit')
    op.drop_table('hackathons')
    # ### end Alembic commands ###
