const fs = require('fs');
const path = require('path');

const SECTIONS_DIR = path.join(__dirname, '../sections');
const OUTPUT_FILE = path.join(__dirname, '../../AGENT.md');

const SECTIONS_ORDER = [
  'identity.md',
  'philosophy.md',
  'solana-principles.md',
  'tech-stack.md',
  'architecture.md',
  'best-practices.md',
  'ux.md',
  'constraints.md',
  'mistakes.md',
  'hackathon.md',
  'project-guidance.md'
];

function summarize() {
  console.log('Synthesizing AGENT.md...');
  
  let content = '# JudgeChain: AI Development Agent\n\n';
  content += '> This file is auto-generated by .agent/scripts/summarize.js. Do not edit directly.\n\n';

  SECTIONS_ORDER.forEach(file => {
    const filePath = path.join(SECTIONS_DIR, file);
    if (fs.existsSync(filePath)) {
      const sectionContent = fs.readFileSync(filePath, 'utf8');
      content += sectionContent + '\n\n---\n\n';
    } else {
      console.warn(`Warning: Section file ${file} not found.`);
    }
  });

  fs.writeFileSync(OUTPUT_FILE, content);
  console.log(`Successfully generated ${OUTPUT_FILE}`);
}

summarize();
