const fs = require('fs');
const path = require('path');

const SECTIONS_DIR = path.join(__dirname, '../sections');
const OUTPUT_FILE = path.join(__dirname, '../../AGENT.md');

const SECTIONS_ORDER = [
  'identity.md',
  'philosophy.md',
  'solana-principles.md',
  'tech-stack.md',
  'architecture.md',
  'best-practices.md',
  'ux.md',
  'constraints.md',
  'mistakes.md',
  'hackathon.md',
  'project-guidance.md',
  'logging-workflow.md'
];

const AGENTS_DIR = path.join(__dirname, '../agents');

function summarize() {
  console.log('Synthesizing AGENT.md...');
  
  let content = '# JudgeChain: AI Development Agent\n\n';
  content += '> This file is auto-generated by .agent/scripts/summarize.js. Do not edit directly.\n\n';

  // 1. Core Sections
  SECTIONS_ORDER.forEach(file => {
    const filePath = path.join(SECTIONS_DIR, file);
    if (fs.existsSync(filePath)) {
      const sectionContent = fs.readFileSync(filePath, 'utf8');
      content += sectionContent + '\n\n---\n\n';
    } else {
      console.warn(`Warning: Section file ${file} not found.`);
    }
  });

  // 2. Agent Profiles
  if (fs.existsSync(AGENTS_DIR)) {
    content += '# Agent Ecosystem\n\n';
    content += 'The following agent profiles define specific roles for the multi-agent development of JudgeChain.\n\n';
    
    const agentFiles = fs.readdirSync(AGENTS_DIR).filter(f => f.endsWith('.md'));
    agentFiles.forEach(file => {
      const filePath = path.join(AGENTS_DIR, file);
      const agentContent = fs.readFileSync(filePath, 'utf8');
      content += agentContent + '\n\n---\n\n';
    });
  }

  fs.writeFileSync(OUTPUT_FILE, content);
  console.log(`Successfully generated ${OUTPUT_FILE}`);
}

summarize();
